SCHEMA = {

    "users": [
        "id",
        "username",
        "email",
        "password",
        "role",
        "is_active",
        "created_at",
        "updated_at",
    ],

    "company": [
        "id",
        "company_name",
        "about",
        "mission",
        "vision",
        "phone",
        "alternate_phone",
        "email",
        "address",
        "facebook",
        "instagram",
        "linkedin",
        "youtube",
        "logo",
        "favicon",
        "created_at",
        "updated_at",
    ],

    "categories": [
        "id",
        "name",
        "slug",
        "display_order",
        "is_active",
        "created_at",
        "updated_at",
    ],

    "projects": [
        "id",
        "category_id",
        "title",
        "slug",
        "short_description",
        "description",
        "location",
        "builder",
        "status",
        "price",
        "rera_number",
        "thumbnail",
        "is_featured",
        "display_order",
        "created_at",
        "updated_at",
    ],

    "project_images": [
        "id",
        "project_id",
        "image_path",
        "image_type",
    ],

    "amenities": [
        "id",
        "project_id",
        "title",
    ],

    "services": [
        "id",
        "title",
        "slug",
        "content",
        "image_path",
        "display_order",
        "is_active",
        "created_at",
        "updated_at",
    ],

    "enquiries": [
        "id",
        "name",
        "email",
        "phone",
        "subject",
        "message",
        "project_id",
        "is_read",
        "created_at",
    ],
}